# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TosGJKGfPf0LXcM7A3BmI3NAwNt8okOm
"""

!apt-get install -y python3.11 python3.11-venv cargo rustc -qq

!python3.11 -m venv /content/venv311
!/content/venv311/bin/python -m pip install --upgrade pip -q

!/content/venv311/bin/pip install torch torchaudio --index-url https://download.pytorch.org/whl/cu121 -q
!/content/venv311/bin/pip install deepfilternet==0.5.6 soundfile -q

from google.colab import files
print("Upload your noisy audio file:")
uploaded = files.upload()
noisy_filename = list(uploaded.keys())[0]

script = f"""
from df.enhance import enhance, init_df, load_audio, save_audio

model, df_state, _ = init_df()

audio, _ = load_audio("{noisy_filename}", sr=df_state.sr())
enhanced = enhance(model, df_state, audio)

save_audio("enhanced_output.wav", enhanced, df_state.sr())
print("Done — enhanced_output.wav created")
"""

with open("run_enhance.py", "w") as f:
    f.write(script)

!/content/venv311/bin/python run_enhance.py

from IPython.display import Audio, display
print("Original (noisy):")
display(Audio(noisy_filename))
print("Enhanced:")
display(Audio("enhanced_output.wav"))

files.download("enhanced_output.wav")